[project]
name = "hello_world"
version = "2024.0.1"

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'

[tool.autopep8]
max_line_length = 88

[tool.pyright]
venv = "venv"
venvPath = "."
pythonVersion = "3.12"
